# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "dek-mvp-09onboarding" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      we_090: "Gressier, Haiti"
      need_090: "Creative Freedom"
      # Platform Ecosystem: What nonprofit is the basis of design for your platform's OWNER?
      go_090: "Urban Growers Collective"
      search_090: "[Eukaryotic Cell: Membrane]"
      find_090: "Water: Cymatics - 174 Hz"
      take_090: "Backstage"
      return_090: "A City-Building Ecosystem"
      changed_090: "ourStory: Everything Is Music"
      
      we_091: "Indigenous Designers"
      need_091: "Creative Freedom"
      # Platform Interface: What city agency is the basis of design for your platform's PROVIDER?
      go_091: "Chicago Department of Planning and Development"
      search_091: "The Planet: Van Allen Belt"
      find_091: "Government Institution: Language"
      # What AI ecosystem will you learn from?
      take_091: "Hugging Face"
      return_091: "City Agency (AgenCity) Intelligence Library"
      changed_091: "hu3agency: we're all right"
      we_092: "Permaculture Engineers"
      
      need_092: "Creative Freedom"
      # Platform Team: What open source community is the basis of design for your platform's PRODUCERS?
      go_092: "Open Source Community Africa"
      search_092: "Tree: Bark"
      find_092: "Family Institution: Universal Chakra"
      # What blockchain ecosystem will you learn from?
      take_092: "Web3 Foundation"
      return_092: "City Block Planning Studio"
      changed_092: "lp0_polymathProcess"

      we_093: "SolarPunk Design Engineers"
      need_093: "Creative Freedom"
      # Platform Project: What company is the basis of design for your platform's CONSUMERS?
      go_093: "ICON"
      search_093: "Human: Integumentary System"
      find_093: "Business Institution: Chief Language Office (CLO)"
      # What park ecosystem will you learn from?
      take_093: "Chicago Boulevard System"
      return_093: "Niche Construction University"
      changed_093: "ep0_daoTeaching"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

